name: 'Autosquash'
description: 'Autosquash commits in PR.'
author: 'Juraj Piar <juraj.piar@icloud.com>'
inputs:
  github_token:
    description: Token for the GitHub API.
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
